---
title: "Compare Results"
author: "Audrey Smith"
date: "6/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, include = FALSE}
library(ggplot2)
library(dplyr)
library(lubridate)
library(stringr)
library(httr)
library(jsonlite)

source('source_scripts/a_general_purpose_setup.R')
source('source_scripts/b_airnow_api_call.R')
```

### Prepare Data
```{r}
params_aq <- read.csv("../aeroqual/2021-06/pse_calvals_2021-06.csv")

param_paths_pse_all_O3 <- list.files('results', 'OZONE*', full.names = T)
param_path_pse_current_O3 <- param_paths_pse_all_O3[length(param_paths_pse_all_O3)]
params_pse_O3 <- read.csv(param_path_pse_current_O3)

param_paths_pse_all_NO2 <- list.files('results', 'NO2*', full.names = T)
param_path_pse_current_NO2 <- param_paths_pse_all_NO2[length(param_paths_pse_all_NO2)]
params_pse_NO2 <- read.csv(param_path_pse_current_NO2)

raw_data <- read.csv('raw_data/raw_60_min.csv') %>%
  filter(ID %in% c('AQY BB-633', 'AQY BB-642'))
```

```{r}
proxy_O3 <- get_current_proxy_data('OZONE')

proxy_NO2 <- get_current_proxy_data('NO2')
```

```{r}
O3_data_aq <- inner_join(params_aq, raw_data, by = 'ID') %>%
  filter(ID %in% c('AQY BB-633', 'AQY BB-642')) %>%
  filter(Time >= deployment_date & Time >= start_date & Time <= end_date & Time < 2021) %>%
  transmute(ID=ID, TIME=Time, O3.RAW = O3_raw,
            O3.AQ = round(O3.gain*(O3_raw - O3.offset), 2),
            O3.GAIN.AQ=O3.gain, O3.OFFSET.AQ=O3.offset)

O3_data_pse <- inner_join(params_pse_O3, raw_data, by = 'ID') %>%
  filter(ID %in% c('AQY BB-633', 'AQY BB-642')) %>%
  filter(Time >= deployment_date & Time >= start_date & Time <= end_date & Time < 2021) %>%
  transmute(ID=ID, TIME=Time,
            O3.PSE = round(O3.offset + O3.gain*O3_raw, 2),
            O3.GAIN.PSE=O3.gain, O3.OFFSET.PSE=O3.offset)

O3_data <- inner_join(O3_data_aq, O3_data_pse, by = c('ID', 'TIME')) %>%
  inner_join(., proxy_O3, by = c('TIME'='timestamp_pacific')) %>%
  mutate(TIMESTAMP = ymd_hms(TIME), O3.PROXY = round(proxy_rand, 2)) %>%
  dplyr::select(ID, TIME, TIMESTAMP, O3.RAW, O3.PROXY, O3.AQ, O3.PSE, O3.GAIN.AQ, O3.GAIN.PSE, O3.OFFSET.AQ, O3.OFFSET.PSE) %>%
  filter(O3.GAIN.PSE != 1)
```

```{r}
NO2_data_aq <- inner_join(params_aq, raw_data, by = 'ID') %>%
  filter(ID %in% c('AQY BB-633', 'AQY BB-642')) %>%
  filter(Time >= deployment_date & Time >= start_date & Time <= end_date & Time < 2021) %>%
  mutate(O3.AQ = O3.gain*(O3_raw - O3.offset), OX.AQ = Ox.gain*(Ox_raw - Ox.offset), NO2.INT = OX.AQ-NO2.a.value*O3.AQ) %>%
  transmute(ID=ID, TIME=Time, NO2.GAIN.AQ=NO2.gain, NO2.OFFSET.AQ=NO2.offset, NO2.AQ = round(NO2.gain*(NO2.INT - NO2.offset), 2))
  
NO2_data_pse <- inner_join(params_pse_O3, raw_data, by = 'ID') %>%
  filter(ID %in% c('AQY BB-633', 'AQY BB-642')) %>%
  filter(Time >= deployment_date & Time >= start_date & Time <= end_date & Time < 2021) %>%
  transmute(ID=ID, TIME=Time, NO2.RAW = NO2_raw, Ox.RAW = Ox_raw, O3.PSE = round(O3.offset + O3.gain*O3_raw, 2)) %>%
  inner_join(params_pse_NO2, by = 'ID') %>%
  filter(TIME >= deployment_date & TIME >= start_date & TIME <= end_date & TIME < 2021) %>%
  transmute(ID=ID, TIME=TIME, NO2.RAW=NO2.RAW, 
            NO2.PSE = round(NO2.offset + NO2.gain.Ox*Ox.RAW - NO2.gain.O3*O3.PSE, 2),
            NO2.GAIN.PSE=NO2.gain.Ox, NO2.OFFSET.PSE=NO2.offset)

NO2_data <- inner_join(NO2_data_pse, proxy_NO2, by = c('TIME'='timestamp_pacific')) %>%
  inner_join(NO2_data_aq, by = c('ID', 'TIME')) %>%
  mutate(TIMESTAMP = ymd_hms(TIME), NO2.PROXY = round(proxy_rand, 2)) %>%
  dplyr::select(ID, TIME, TIMESTAMP, NO2.RAW, NO2.PROXY, NO2.PSE, NO2.AQ, NO2.GAIN.PSE, NO2.GAIN.AQ, NO2.OFFSET.PSE, NO2.OFFSET.AQ) %>%
  filter(NO2.GAIN.PSE != 1)
```

### Write Functions to Examine Performance
```{r}
get_timeseries <- function(input_data, aqy_id, month.i, pollutant){
  
  timeseries_plot <- ggplot(input_data) +
      geom_line(aes(x = TIMESTAMP, y = POL.RAW, color = 'raw')) +
      geom_line(aes(x = TIMESTAMP, y = POL.PROXY, color = 'proxy')) +
      geom_line(aes(x = TIMESTAMP, y = POL.AQ, color = 'aeroqual')) +
      geom_line(aes(x = TIMESTAMP, y = POL.PSE, color = 'pse')) +
      labs(title = paste(pollutant, 'Timeseries', '-', aqy_id, 'Month of', month.i), 
           x = 'Timestamp', y = paste('Pollutant Concentration (ppb)')) +
      theme(plot.title = element_text(hjust = .5))
  
  print(timeseries_plot)
  
}
```

```{r}
get_error_timeseries <- function(input_data, aqy_id, month.i, pollutant){
  
  error_timeseries <- input_data %>%
    mutate(AE.RAW = POL.RAW - POL.PROXY, AE.AQ = POL.AQ - POL.PROXY, AE.PSE = POL.PSE - POL.PROXY) %>%
    ggplot() +
    geom_line(aes(x = TIMESTAMP, y = AE.RAW, color = 'raw')) +
    geom_line(aes(x = TIMESTAMP, y = AE.AQ, color = 'aeroqual')) +
    geom_line(aes(x = TIMESTAMP, y = AE.PSE, color = 'pse')) +
    labs(title = paste('Absolute Error for', pollutant, '-', aqy_id, 'month of', month.i), 
         x = 'Timestamp', y = 'Absolute Error (ppb)') +
    theme(plot.title = element_text(hjust = .5))
  
  print(error_timeseries)
  
}
```

```{r}
get_scatterplot <- function(input_data, aqy_id, month.i, pollutant){
  
  scatterplot <- ggplot(input_data) +
      geom_line(aes(x = POL.PROXY, y = POL.PROXY, color = '1-to-1 fit')) +
      geom_point(aes(x = POL.PROXY, y = POL.RAW, color = 'raw'), alpha = .5) +
      geom_point(aes(x = POL.PROXY, y = POL.PSE, color = 'pse'), alpha = .5) +
      geom_point(aes(x = POL.PROXY, y = POL.AQ, color = 'aeroqual'), alpha = .5) +
      labs(title = paste(pollutant, '[Proxy] vs [Measured] for', aqy_id, 'month of', month.i), 
           x = 'Timestamp', y = 'Pollutant Concentration - (ppb)') +
      theme(plot.title = element_text(hjust = .5))
      
    print(scatterplot)

}
```

```{r}
get_lms <- function(input_data, aqy_id, month.i){
  
  model_raw <- summary(lm('POL.PROXY~POL.RAW', data = input_data))
  model_pse <- summary(lm('POL.PROXY~POL.PSE', data = input_data))
  model_aq <- summary(lm('POL.PROXY~POL.AQ', data = input_data))
  
  r_sq <- data.frame(cbind(month.i, round(model_raw$r.squared, 5), round(model_pse$r.squared, 5), round(model_aq$r.squared, 5)))
  colnames(r_sq) <- c('month', 'raw', 'PSE', 'AQ')
  
  return(r_sq)
}
```

```{r}
get_offset_timeseries <- function(input_data, aqy_id, pollutant){
  
  offset_timeseries <- ggplot(input_data) +
    geom_line(aes(x = TIMESTAMP, y = POL.OFFSET.PSE, color = 'pse')) +
    geom_line(aes(x = TIMESTAMP, y = POL.OFFSET.AQ, color = 'aeroqual'))  +
    ggtitle(paste(pollutant, 'Offset Over Time for', aqy_id)) +
    theme(plot.title = element_text(hjust = .5))
  
  print(offset_timeseries)
}
```

```{r}
get_gain_timeseries <- function(input_data, aqy_id, pollutant){
  
  gain_timeseries <- ggplot(input_data) +
    geom_line(aes(x = TIMESTAMP, y = POL.GAIN.PSE, color = 'pse')) +
    geom_line(aes(x = TIMESTAMP, y = POL.GAIN.AQ, color = 'aeroqual')) +
    ggtitle(paste(pollutant, 'Gain Over Time for', aqy_id)) +
    theme(plot.title = element_text(hjust = .5))
  
  print(gain_timeseries)
  
}
```

```{r}
get_r2_plot <- function(input_data, aqy_id, pollutant){
  
  r2_plot <- ggplot(input_data) +
    geom_line(aes(x = as.numeric(month), y = as.numeric(AQ), color = 'aeroqual')) +
    geom_line(aes(x = as.numeric(month), y = as.numeric(PSE), color = 'pse')) +
    labs(x = 'Month', y = 'R^2', 
         title = paste(pollutant, 'Proxy ~ Measured R^2 Over Time for', aqy_id))  +
    theme(plot.title = element_text(hjust = .5))
  
  print(r2_plot)
}
```

### Run Performance Tests
```{r}
months <- c('07', '08', '09', '10', '11', '12')
```

```{r}
make_all_plots <- function(input_data, aqy_id, pollutant){
  
  colnames(input_data) <- str_replace_all(colnames(input_data), pollutant, 'POL')
  
  monthly_models <- data.frame()
  
  for(month.i in months){
    
    data_for_month <- filter(input_data, ID == aqy_id & TIME >= paste0('2020-', month.i, '-01 00:00:00') & TIME <= paste0('2020-', month.i, '-31 23:59:59'))
    
    get_timeseries(data_for_month, aqy_id, month.i, pollutant)
    
    get_error_timeseries(data_for_month, aqy_id, month.i, pollutant)
    
    get_scatterplot(data_for_month, aqy_id, month.i, pollutant)
    
    month.i_model <- get_lms(data_for_month, aqy_id, month.i)
    monthly_models <- rbind(monthly_models, month.i_model)
    
  }
  
  data_for_deployment <- filter(input_data, ID == aqy_id)
  
  overall_model <- get_lms(data_for_deployment, aqy_id, 'Full Deployment')
  all_models <- rbind(overall_model, monthly_models)
  print(all_models)
  
  get_r2_plot(monthly_models, aqy_id, pollutant)
  
  get_offset_timeseries(data_for_deployment, aqy_id, pollutant)
  
  get_gain_timeseries(data_for_deployment, aqy_id, pollutant)
  
}
```

```{r}
make_all_plots(O3_data, 'AQY BB-633', 'O3')
```

```{r}
make_all_plots(O3_data, 'AQY BB-642', 'O3')
```

```{r}
make_all_plots(NO2_data, 'AQY BB-633', 'NO2')
```

```{r}
make_all_plots(NO2_data, 'AQY BB-642', 'NO2')
```


### MANUAL PLOTS
```{r}
get_scatter_facet_aqy <- function(in_data, pollutant, aqy_id){
  
  colnames(in_data) <- str_replace_all(colnames(in_data), pollutant, 'POL')
  
  scatter_facet <- in_data %>%
    filter(ID == aqy_id) %>%
    mutate(MONTH = month(TIMESTAMP, label = T, abbr = F), .after = 'TIMESTAMP') %>%
      ggplot() + 
      geom_line(aes(x = POL.PROXY, y = POL.PROXY, color = '1-to-1 Fit')) +
      geom_point(aes(x = POL.PROXY, y = POL.RAW, color = 'Raw'), size = .5, alpha = .5) +
      geom_point(aes(x = POL.PROXY, y = POL.AQ, color = 'Aeroqual'), size = .5, alpha = .5) +
      geom_point(aes(x = POL.PROXY, y = POL.PSE, color = 'PSE'), size = .5, alpha = .5) +
      labs(x = 'Proxy Concentration (ppb)', y = 'Measured Concentration (ppb)', title = paste('Calibrated', pollutant, '& Proxy Values - ', aqy_id)) +
      theme(plot.title = element_text(hjust = .5)) +
      facet_wrap(~MONTH)
  
  return(scatter_facet)
}

get_scatter_facet_aqy(O3_data, 'O3', 'AQY BB-633')
get_scatter_facet_aqy(O3_data, 'O3', 'AQY BB-642')

get_scatter_facet_aqy(NO2_data, 'NO2', 'AQY BB-633')
get_scatter_facet_aqy(NO2_data, 'NO2', 'AQY BB-642')
```

```{r}

```
























